### PR TITLE
Added main styles wireframe

### PR DESCRIPTION
**Pull request by georgeutsin**
Todo: clean everything up

### CODE REVIEW

**Comment by georgeutsin** [comment]
This will fail tests but I just wanted to get the styles in a PR asap. Very bare, but its something

**Comment by JamesHageman** [comment]
Cool, I'll pull it down and fix the tests

**Comment by georgeutsin** [comment]
Lit

**Comment by georgeutsin** [comment]
I will literally redo everything after midterms just to make it clear

**Comment by JamesHageman** [comment]
:shipit:

**Pull request merged**
