### PR TITLE
33: Add more hover details to broadcasts

### LINKED ISSUE #33: Add time_ago to broadcasts on hover
Also, show the right data like the display name, username, possible rebroadcast username and time ago (see reference on v1 of the site)

### PR DESCRIPTION
**Pull request by ethan-hardy**
Closes #33
Display broadcast / rebroadcast date(s) and potential rebroadcaster

### CODE REVIEW

**Comment by JamesHageman** [comment]
@ethan-hardy Can you rebase with master so we get codecov? Also, can you hide the date on broadcasts when you aren't hovering over them?

**Comment by JamesHageman** [comment]
:shipit:

**Comment by georgeutsin** [comment]
screen shot 2016-11-24 at 9 39 48 pm
Hovering over a broadcast just created hangs the loading screen, then errors out. Rehovering gives that error and doesn't show the broadcast owner

**Comment by ethan-hardy** [comment]
@georgeutsin should be fixed now

**Comment by JamesHageman** [comment]
pls merge

**Pull request merged**
